/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "kotlin-projects"
include("app")
include("anotherApp")
include("javafx-app1")
include("javafx-app2")

// set up parallel execution, using all available threads
gradle.startParameter.isParallelProjectExecutionEnabled = true
// set up the maximum number of parallel threads to use
gradle.startParameter.maxWorkerCount = Runtime.getRuntime().availableProcessors() / 2
// display the number of parallel threads used
println("=== Using ${gradle.startParameter.maxWorkerCount} parallel threads for execution. = ==")