/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue


class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test fun appIsObject() {
        val classUnderTest = App
        assertTrue(classUnderTest.javaClass.isInstance(App))
    }
}
